language: java
dist: bionic
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf $HOME/.m2/repository/com/appsflyer/
install: skip
script: "./src/main/resources/build-ci.sh"
notifications:
  email:
    - yaron.elyashiv@appsflyer.com
