language: java
dist: bionic
jdk: openjdk11
cache:
  directories:
    - $HOME/.m2
after_success:
  - lein coveralls
  - mvn jacoco:report coveralls:report
notifications:
  email:
    - yaron.elyashiv@appsflyer.com
