language: java
dist: bionic
jdk: openjdk11
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/com/appsflyer/
after_success:
  - lein coveralls
  - mvn jacoco:report coveralls:report
notifications:
  email:
    - yaron.elyashiv@appsflyer.com
