language: java
sudo: required
dist: bionic
jdk: openjdk11
cache:
  directories:
    - $HOME/.m2
after_success:
  - lein cloverage -o target --coveralls --emma-xml --junit
  - mvn jacoco:report coveralls:report
notifications:
  email:
    - yaron.elyashiv@appsflyer.com
