language: java
dist: bionic
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf $HOME/.m2/repository/com/appsflyer/
install: skip
jobs:
  include:
    - stage: test
      name: "Java & Clojure Tests and Coverage Report"
      script: "./build-ci.sh"
    - stage: deploy
      name: "Deploy Snapshot"
      if: type != pull_request AND env(CLOJARS_USERNAME) IS present
      script: bash .travis.deploy.snapshot.sh
notifications:
  email:
    recipients:
      secure: hWc/40fUbU44i7KeYPXTC356TJvxSZKdhEfiJFizT1nVcyhFoloEiypvSKu6BkCG1BwAtxdkjT+r+B9fKb6TRjFhUDHlXXL/EzzLCSZkzYpCWGTyl0ImeKSD41vou7icfeWfnnd8nrJRMfcdr2kKzZ2NifafpVVLJefBDSxXhZ1lsFKILslVR6xQ0UHFwVm7cPOD2S/0GtoM9g/ndFTYDmteRpzmQxfn/8mIqB2V7Kt3+RAVAyTeYS8824E22PnivB8slVWuy5//uepROafdpbDeRvCwluXzc6zBLmL0g7esae/XMSMwJ+NcjiP8gjYehsiLDdR+hl5L4XFtcNAXOs6C5xbNqXBn9E1reh0PsA4SbxE1/uBhTTilAZY2Bv4A0LrPSgJUPAflyrDABm6gcoPeaxyWrWZxR+Ck4NY8KzNuK3ZowR6/RjO+NH3F5sY+iM1IsGd0uRjECQ24xfnCa1CmqoyJUXWUcssA1U07AF3oEWnDeWYGzlw1tyjsLCGILnJs7kHiXauW+l0lMmQFhrRHGy5VkeLovfZKG5JqbUAluQu/QaulZ2h4y+vPYo7oN+Zi32ZL8qP1Abr115oG8iaOy6gsOwo/0BbCXWbICSAXOMqIkK+YeB316jEW0RV6DMpLpDpQ0SUyQwRcDByjKH/Ae68KVQbpLG3MtnPAXcc=
