name: Donkey CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.head_ref }}
      PULL_REQUEST: ${{ github.event_name == pull_request }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Java & Clojure Tests and Coverage Report"
        run: ./build-ci.sh
      #      - name: "Output github vars"
      #        run: echo "${{ toJson(github) }}"
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          path-to-lcov: target/coveralls/coveralls.json
#      - name: "Deploy Snapshot"
#        env:
#          CLOJARS_USERNAME: appsflyer
#        if: type != pull_request AND secrets.CLOJARS_PASSWORD IS present
#        run: |
#          echo "::set-env name=BRANCH::${BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}"
#          bash .ci.deploy.snapshot.sh
