name: Donkey CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "Java & Clojure Tests and Coverage Report"
        run: ./build-ci.sh
      - name: "Output github vars"
        run: echo "${{ toJson(github) }}"
#      - name: "Deploy Snapshot"
#              if: type != pull_request AND env(CLOJARS_USERNAME) IS present
#              script: bash .travis.deploy.snapshot.sh
